---
# Распаковка live-системы в цель (офлайн-установка, интернет не нужен).
# install_dir=appleos задан в arch-profile/profiledef.sh
unpack:
- source: "/run/archiso/bootmnt/appleos/boot/x86_64/airootfs.sfs"
  sourcefs: "squashfs"
  destination: ""
