---
defaultGroups:
- wheel
- audio
- video
- optical
- storage
- network
- power
autologinGroup: autologin
setRootPassword: ask
availableShells: [/bin/bash, /bin/zsh, /bin/fish]
defaultShell: /bin/bash
