#!/bin/bash
# AppleOS USB via GRUB2 (BIOS) — for old machines where syslinux fails with
# "failed to load ldlinux.c32" but the ISO itself is fine (proven in QEMU/VM).
# Copies the ISO tree onto a FAT32 stick and installs GRUB i386-pc, whose own
# USB driver works where syslinux gives up. Also boots on UEFI (fallback EFI).
# Usage: sudo ./scripts/install-usb-grub.sh <appleos.iso> </dev/sdX>
# DANGER: the whole target device is wiped. Triple-check the device letter!
set -euo pipefail

ISO="${1:-}"
DEV="${2:-}"
[ -n "$ISO" ] && [ -f "$ISO" ] || { echo "usage: sudo $0 <appleos.iso> </dev/sdX>"; exit 1; }
[ -n "$DEV" ] && [ -b "$DEV" ] || { echo "ERROR: $DEV is not a block device"; exit 1; }
if [ "$(id -u)" -ne 0 ]; then exec sudo "$0" "$@"; fi

for t in sfdisk mkfs.vfat grub-install xorriso lsblk; do
  command -v "$t" >/dev/null 2>&1 || {
    echo "ERROR: missing '$t'."
    echo "  Arch:   sudo pacman -S --needed util-linux dosfstools grub xorriso"
    echo "  Ubuntu: sudo apt install fdisk dosfstools grub-pc xorriso"
    exit 1
  }
done

echo "=== target device ==="
lsblk -d -o NAME,MODEL,SIZE,TRAN "$DEV"
echo "=== mounted partitions (will be unmounted) ==="
lsblk -ln -o NAME,MOUNTPOINT "$DEV" | awk '$2!=""{print}'
echo ""
echo "WARNING: ALL DATA on $DEV will be DESTROYED."
read -rp "Type YES in capitals to continue: " CONFIRM
[ "$CONFIRM" = "YES" ] || { echo "aborted."; exit 1; }

# Unmount everything on this device (mountpoints may contain spaces!).
# Lazy (-l) because file managers (nautilus) often hold the mount busy.
while IFS= read -r m; do
  if [ -n "$m" ]; then umount -l "$m" 2>/dev/null || true; fi
done < <(lsblk -ln -o MOUNTPOINT "$DEV" 2>/dev/null | grep . || true)
swapoff $(lsblk -ln -o NAME,MOUNTPOINT "$DEV" 2>/dev/null | awk '$1~/swap/{print}') 2>/dev/null || true

echo "[usb] partitioning $DEV (MBR, single FAT32 bootable)..."
# Wipe all old signatures first (Ventoy/DD leftovers: ISO9660 PVD, GPT backup).
# Otherwise blkid/grub see "multiple partition maps" and refuse to work.
wipefs --all --force "$DEV" >/dev/null 2>&1 || true
printf 'label: dos\nstart=2048, type=c, bootable\n' | sfdisk --force "$DEV"
PART="${DEV}1"
[[ "$DEV" =~ [0-9]$ ]] && PART="${DEV}p1"   # mmcblk/nvme naming
# Wait until the kernel actually re-reads the table (old firmware sticks are slow)
for _i in $(seq 1 15); do
  partprobe "$DEV" 2>/dev/null
  sleep 2
  [ -b "$PART" ] && break
done
[ -b "$PART" ] || { echo "ERROR: kernel did not pick up $PART — unplug/replug and retry"; exit 1; }
mkfs.vfat -F 32 -n APPLEOS "$PART"

MNT="$(mktemp -d /tmp/appleos-usb.XXXXXX)"
mount "$PART" "$MNT"
cleanup() { umount "$MNT" 2>/dev/null; rmdir "$MNT" 2>/dev/null; }
trap cleanup EXIT

echo "[usb] extracting ISO tree (this takes a while, ~3 GB)..."
xorriso -osirrox on -indev "$ISO" -extract / "$MNT" 2>&1 | tail -2

UUIDFILE="$(ls "$MNT"/boot/*.uuid 2>/dev/null | head -1)"
[ -n "$UUIDFILE" ] || { echo "ERROR: no uuid file in ISO /boot (not an archiso?)"; exit 1; }
UUID="$(basename "$UUIDFILE" .uuid)"
echo "[usb] archiso uuid: $UUID"

echo "[usb] writing GRUB config..."
mkdir -p "$MNT/boot/grub"
cat > "$MNT/boot/grub/grub.cfg" <<EOF
# AppleOS USB (GRUB BIOS) — generated by install-usb-grub.sh
set timeout=10
set default=0

menuentry "AppleOS install medium (USB)" {
  linux /arch/boot/x86_64/vmlinuz-linux archisobasedir=arch archisosearchuuid=$UUID console=tty0 console=ttyS0,115200
  initrd /arch/boot/x86_64/initramfs-linux.img
}

menuentry "AppleOS install medium (USB, verbose)" {
  linux /arch/boot/x86_64/vmlinuz-linux archisobasedir=arch archisosearchuuid=$UUID debug console=tty0 console=ttyS0,115200
  initrd /arch/boot/x86_64/initramfs-linux.img
}
EOF

echo "[usb] installing GRUB i386-pc to $DEV ..."
grub-install --target=i386-pc --boot-directory="$MNT/boot" --recheck "$DEV" 2>&1 | tail -2

sync
umount "$MNT"; rmdir "$MNT"; trap - EXIT
echo ""
echo "=== DONE: $DEV is an AppleOS USB stick (BIOS GRUB + UEFI fallback) ==="
lsblk -o NAME,SIZE,FSTYPE,LABEL "$DEV"
